### ISSUE TITLE
[Question] How to set up AAD B2C for main API and AAD for docs?

### ISSUE THREAD

**Issue by leranjun** [Intility/fastapi-azure-auth#109]
Hi! I'm new to Azure and AAD, so please correct me if I'm wrong.

I see that this package supports AAD B2C, but I haven't found any related documentation other than the sample project.

Basically, I would like to limit the main API to registered users in a B2C directory and the Swagger docs to users in the main directory (i.e. admins). Is that possible? Thanks.

**Comment by JonasKs** [comment]
Unfortunately the documentation for B2C is lacking.  @kristiqntashev added tests and support - would you be up to document Azure setup too? Or you, @leranjun if you made it work? 

As for APIs to be restricted, you should use roles in Azure. There's docs on how to do that [here](https://intility.github.io/fastapi-azure-auth/usage-and-faq/locking_down_on_roles).

**Comment by leranjun** [comment]
Thanks for the reply! Is it possible for only the Swagger docs to be restricted, though? Or does it only apply to main API routes? I don't seem to see a dependency configuration for docs.

**Comment by JonasKs** [comment]
Swagger is just a client to call your APIs, there's no "swagger API" and "normal API". So if I interpret your question correctly, and you want to hide swagger docs behind authentication, then no, that's not possible (and would be security by obscurity, which is pretty useless). Your APIs should have authentication, and swagger is just a client that can call your APIs, and help you fetch a valid token.

**Comment by JonasKs** [comment]
Of course you can always host a custom swagger, or customize the one fastapi generates, but there's no security in that. 

See https://fastapi.tiangolo.com/advanced/extending-openapi/.

**Comment by leranjun** [comment]
Gotcha, super helpful! I think I'll need to dig a bit deeper into what I actually want to achieve. Thank you both for the comments.

**Comment by JonasKs** [comment]
@kristiqntashev that sounds awesome! Let me know if you need any help with docs! 😊

**Comment by JonasKs** [comment]
I'll close this for now. Please don't hesitate re-opening or creating a new issue if you have more questions, @leranjun
