### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by dorlugasigal** [Intility/fastapi-azure-auth#114]
**Describe the feature you'd like**
would be great if an auto-refresh token feature would be added to this repository
maybe an additional flag of execution, 
in addition to that, would be great if you could control which part of the JWT you'd want to validate
these could get inside as a `authentication_flow_settings` or so

id be happy to implement that

**Comment by JonasKs** [comment]
> would be great if an auto-refresh token feature would be added to this repository

Sorry, that’s outside the scope of this library, we only intend to validate tokens, not fetching them. 

> in addition to that, would be great if you could control which part of the JWT you'd want to validate

Not sure what you‘re actually asking here.

**Comment by dorlugasigal** [comment]
> > would be great if an auto-refresh token feature would be added to this repository
> 
> Sorry, that’s outside the scope of this library, we only intend to validate tokens, not fetching them.
> 
> > in addition to that, would be great if you could control which part of the JWT you'd want to validate
> 
> Not sure what you‘re actually asking here.

Too bad

Anyway,
Was talking about claims, you have an option object with boolean flags for each claim you want to validate

**Comment by JonasKs** [comment]
We validate the token and it's signature. What you do with roles or claims is up to you, you can create dependencies to check roles or claims. 

https://github.com/Intility/fastapi-azure-auth/blob/main/demo_project/api/dependencies.py#L27

https://github.com/Intility/fastapi-azure-auth/blob/main/fastapi_azure_auth/user.py#L6
