### ISSUE TITLE
[Question] How to use roles?

### ISSUE THREAD

**Issue by r3r00t3d** [Intility/fastapi-azure-auth#117]
I'm using the 3.5.1 version of the library. For some reason, roles array is always empty inside the User object even though my user has 10 roles assigned in Azure AD. I'm trying to debug an issue and I cannot find a way to resolve if this is an Azure issue or a library issue. All of the other information inside the User object are filled out correctly. 

Is there some special permission needed or anything that you can provide that can point me in the right direction? My user is also a member of a Global Administrator group, so it has the highest available privileges in the tenant.

Thanks.

**Comment by JonasKs** [comment]
Hi, 

Typing this on my phone, so no screenshots (I can help more tomorrow), but from memory:

- Go to your application registration
- roles 
- Create a new role
- Go to the enterprise application (you can go to overview -> click the name of the appreg, it'll take you there) 
- map your users/enterprise roles to the app role

I can give a small tutorial tomorrow when I'm on a laptop. 😊

**Comment by optimo-tandros** [comment]
Thanks, I'll try that and I really appreciate all the help.

**Comment by JonasKs** [comment]
Go to your application registration, click `Groups`:  
![image](https://user-images.githubusercontent.com/5310116/224047069-da296071-1fb3-437b-a408-f3d5d5cd423a.png)


Create a role: 

![image](https://user-images.githubusercontent.com/5310116/224047211-d905661d-c889-41a1-a639-8d9692cb6fcc.png)


Go to Overview and click the Enterprise application link:  
![image](https://user-images.githubusercontent.com/5310116/224047472-64108d49-49e5-4646-9f45-8114556ce11c.png)

Go to `Users and groups` and add a user/group:

![image](https://user-images.githubusercontent.com/5310116/224047602-a3f5aba6-637c-4571-8998-ff96bf530bbd.png)

Add the user/group that you want to have this role (if you use a group, the users must be a direct member of that group. Nested membership does _not_ work):

![image](https://user-images.githubusercontent.com/5310116/224047945-5eb5f5c0-c8ba-430d-800b-957bdc608068.png)

Click `select role` and assign the user/role to your application role:
![image](https://user-images.githubusercontent.com/5310116/224048183-c2dc3b7b-b227-403a-a42e-a857f00f6efe.png)


Finish by clicking `Assign`. The user will now have that group in their token.

**Comment by r3r00t3d** [comment]
I did this and it worked. Maybe you can put this in the documentation as this will be a very common pattern for developers. The usual thing would be to map application roles with groups and check in the backend if user has certain role based on the group membership.

Thanks again for the detailed answer.

**Comment by JonasKs** [comment]
Pull requests welcome if you'd like to contribute. If not, yes, I will fix 😊

**Comment by JonasKs** [comment]
#200 will solve this issue
