### ISSUE TITLE
[Question/Warning]

### ISSUE THREAD

**Issue by tsw025** [Intility/fastapi-azure-auth#119]
**This is a dep**

fastapi_azure_auth/openid_config.py:5: CryptographyDeprecationWarning: Use PublicKeyTypes instead
  from cryptography.hazmat.primitives.asymmetric.types import PUBLIC_KEY_TYPES as KeyTypes

**To Reproduce**

**Stack trace**
fastapi_azure_auth/openid_config.py:5: CryptographyDeprecationWarning: Use PublicKeyTypes instead
  from cryptography.hazmat.primitives.asymmetric.types import PUBLIC_KEY_TYPES as KeyTypes

Solution:
from cryptography.hazmat.primitives.asymmetric.types import PublicKeyTypes as KeyTypes

Just creating an ticket to get an update when resolved.

**Comment by JonasKs** [comment]
Thanks! PR welcome if you'd like to contribute 😊

**Comment by tsw025** [comment]
Sorry, this is from the latest release of cryptography.
• Updating cryptography (39.0.1 -> 40.0.1)

I will close this as it is not yet updated

**Comment by tsw025** [comment]
Thank you, updated the [PR](https://github.com/Intility/fastapi-azure-auth/pull/120) :smile:
