### ISSUE TITLE
[Feature request] Adding field to the user object

### ISSUE THREAD

**Issue by enadeau** [Intility/fastapi-azure-auth#125]
Is there a rational behind the choice of claims that are made available on the `User` model ? Some of the claims are made available directly on the `User` model and other are hidden inside the claim field.

 I'd like to see more information from the claim made available on the `User` model such as `sub`, `oid`, `preferred_user_name` etc... so they could be used more easily in the app.

 Would you accept a PR going that direction?

**Comment by JonasKs** [comment]
Hi! No, not really, other than what I needed myself. I'm happy to accept a PR which extends these fields. 😊

**Comment by enadeau** [comment]
Great I'll work on that :)

**Comment by JonasKs** [comment]
Awesome! Let me know if I can help with anything.

**Comment by omBratteng** [comment]
I have extended the model a bit, with all claims that I've gathered from [Microsoft Docs for access tokens](https://learn.microsoft.com/en-us/azure/active-directory/develop/access-tokens) and the optional claims you can configure in Azure AD portal.

https://github.com/omBratteng/fastapi-azure-auth/blob/148a39c6b6ce5418d99325817bec0a44dcc2df38/fastapi_azure_auth/user.py

**Comment by omBratteng** [comment]
Just opened a draft PR, if someone wants to continue working on it

**Comment by enadeau** [comment]
Hi nice to see the PR. It's been on my to-do list for the last month but did not come around implementing it. I left some comment on the PR and we can see what @JonasKs thinks. I think I'll still try to do a simpler version that would not be such a breaking change.

**Comment by enadeau** [comment]
I've made a much smaller PR #132 that at least covers my use case and I think could be of use for others. It's not as complete as @omBratteng one's, but I think it is ready to merge.

**Comment by JonasKs** [comment]
Thanks, both of you. I'll look at them both tomorrow. 

First glance on phone, I agree that @omBratteng's PR is breaking.  MyPy won't like us having two different returns, but we can fix that with overloads. 

I do like what he's done to make descriptions very clear, though!   
Also, we could use a default list, if there's no roles, instead of `None`. (Make `user.roles` return `[]` instead, if there are no configured roles)

**Comment by omBratteng** [comment]
As I mentioned in the PR as a comment, I do plan on expanding/ fixing the mypy issues. But I had to stop myself from going down the rabbit hole, I had other things to do first, hence why draft pr.
Perhaps in the next few days, I'll get round to fixing the rest.
