### ISSUE TITLE
poetry add fastapi_azure_auth does not add the package

### ISSUE THREAD

**Issue by mohsspark829** [Intility/fastapi-azure-auth#126]
Hello there, 

Thanks for providing such a detailed documentation. I am trying to add fastapi_azure_auth by poetry and seems it is not possible.

![image](https://user-images.githubusercontent.com/109635633/230101132-e1338db8-497c-48fc-8df7-7c886e00299a.png)

content of  poetry.toml file
[tool.poetry]
name = "fastapi-azure-auth"
version = "0.1.0"
description = ""
authors = ["Tmasked <masked.co.nz>"]
readme = "README.md"
packages = [{include = "fastapi_azure_auth"}]

[tool.poetry.dependencies]
python = "^3.10"
uvicorn = "^0.21.1"
pydantic = {extras = ["dotenv"], version = "^1.10.7"}
fastapi = "^0.95.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

I was wondering if you could assist. I am also trying to find what the problem can be.

Thanks,
Mohsen

**Comment by mohsspark829** [comment]
seems the issue has been solved after changing my poetry project name from "fastapi-azure-auth" to "fastapi-azure-authprj"

**Comment by mohsspark829** [comment]
thanks

**Comment by JonasKs** [comment]
Yes, you cannot name your project the same as a third party package. Glad you fixed it 😊
