### ISSUE TITLE
[Feature request] Accept both token versions

### ISSUE THREAD

**Issue by rhuanbarreto** [Intility/fastapi-azure-auth#129]
**Describe the feature you'd like**

Sometimes your API needs to accept tokens from both versions, for example:

- V2 Tokens for browser/other API calls
- V1 Tokens for azure internal services. When you use system assigned managed identities, the token version issued is V1

Is that possible to accept both token version even though the Swagger UI and other visible UI elements display info only for v2?

**Additional context**

**Comment by JonasKs** [comment]
But yes - this can be fixed and is easy to implement. 

Normally, the backend, when set to v2 tokens only in the manifest, will force all tokens to be v2, even when the token is requested through a v1 token appreg.

**Comment by rhuanbarreto** [comment]
Thanks for the response. I think my request wasn't correct anyway. Sometimes, tokens are created in different contexts and different clientId's. So accepting those kind of tokens is actually wrong.

**Comment by JonasKs** [comment]
> contexts and different clientId's

Sounds like the token would have an audience not intended for your backend? Then yes, that token would be denied regardless of token version. 

I'll close the issue for now, since changing token version in the manifest should enforce all tokens with the audience for your backend to be of v2.

**Comment by JonasKs** [comment]
The graph token is not intended to be accepted, so no matter the token version, it won't work. The `aud` in the token must match your application registration client ID in Azure. 

If you need a graph token, you should use the [OBO flow](https://intility.github.io/fastapi-azure-auth/usage-and-faq/graph_usage).
