### ISSUE TITLE
[Feature request] Docs On How to set up AAD B2C

### ISSUE THREAD

**Issue by akarray** [Intility/fastapi-azure-auth#136]
Hello,
AAD B2C seem to be supported but they is no documentation about how to configure it.
This documentation can save a lot of time.
Can some one add steps for B2C configuration ?
![image](https://github.com/Intility/fastapi-azure-auth/assets/6164073/8ebd4071-52a2-4312-8bf3-974cd7992058)

Thank you

**Comment by davidhuser** [comment]
Also interested in this doc. 

A starting point would be to follow [Azure docs](https://learn.microsoft.com/en-us/azure/active-directory-b2c/configure-authentication-sample-python-web-app?tabs=linux) that shows how to use B2C with MSAL and Flask, then adapt it to use `B2CMultiTenantAuthorizationCodeBearer` as for example used in [this repo](https://github.com/tsdataclinic/data-gather/blob/e682da4d58a809314428160c41bd7d94e299db46/server/api/views.py#L110C16-L110C53). 

Is there anything else to keep in mind?

**Comment by JonasKs** [comment]
I'd say follow the single-tenant steps I've already documented. MSAL works a bit different. 

If you document your steps you can post them here and we can either base the documentation on them, or help you debug.

**Comment by davidhuser** [comment]
out of curiosity, what is the benefit of using the `fastapi-azure-auth` library for B2C over using the the "official" MSAL implementation, e.g. [here](https://github.com/Azure-Samples/ms-identity-python-webapp/blob/main/README_B2C.md)? Is it the targeted implementation for FastAPI?

**Comment by JonasKs** [comment]
> [..] what is the benefit of using the `fastapi-azure-auth` [...]

There are four things a FastAPI backend developer cares about when implementing Azure AD:
* Async fetching of openid config
* Dependency support, so it feels natural to the framework
* Token is validated correctly
* OpenAPI/swagger documentation works, since the user can sign in

As for the official MSAL implementation, I believe it is sync and does not implement any FastAPI framework-specific features such as swagger documentation out of the box by using the dependency. 😊

**Comment by vjmadhal-silverstream** [comment]
Having been through this over the last few days, I found the demo project pretty useful. However, using the B2CMultiTenantAuthorizationCodeBearer I fell foul of invalid issuer. But the docs explain how to implement the issuer verification using the callable. Only problem is that the tid claim isn't available in the B2C token so validating issuer will fail as tid is None, followed by tid not being optional for User (the linked fix already addresses that). Finally, the last hurdle is when validate_iss is true, iss_callable is provided and multi tenant is true (which it is for the B2CMultiTenantAuthorizationCodeBearer) then there's a failure trying to obtain claims.get('tid').
I'll wait on the PR first to see, but the docs are pretty helpful

**Comment by akarray** [comment]
> Having been through this over the last few days, I found the demo project pretty useful. However, using the B2CMultiTenantAuthorizationCodeBearer I fell foul of invalid issuer. But the docs explain how to implement the issuer verification using the callable. Only problem is that the tid claim isn't available in the B2C token so validating issuer will fail as tid is None, followed by tid not being optional for User (the linked fix already addresses that). Finally, the last hurdle is when validate_iss is true, iss_callable is provided and multi tenant is true (which it is for the B2CMultiTenantAuthorizationCodeBearer) then there's a failure trying to obtain claims.get('tid'). I'll wait on the PR first to see, but the docs are pretty helpful

Thank you @vjmadhal-silverstream for your return. There is a nice community using fastapi-azure-auth. PR seem coming very soon. I waiting for it too.

**Comment by davidhuser** [comment]
This is now implemented, refer to the docs 👍

**Comment by JonasKs** [comment]
Thanks again @davidhuser 😊

**Comment by akarray** [comment]
Hello @davidhuser 
Thank's for this great contribution. I had tried exactly all steps in documentation without success

I get this error : 
Auth ErrorError: Bad Request, error: invalid_grant, description: AADB2C90205: This application does not have sufficient permissions against this web resource to perform the operation.

The screen I see seem not exacty as yours :
![image](https://github.com/Intility/fastapi-azure-auth/assets/6164073/b605a19f-f5ad-4c6c-980f-af10fe51148a)

Any idea ?

Thank you
Best Regards

**Comment by davidhuser** [comment]
Hi, make sure the `redirect_uri` matches to your local FastAPI URL (localhost:3000 in the docs vs localhost:7072 in what you provided in the comment above) and try to [Grant Admin consent](https://stackoverflow.com/a/65560606). 

>  And I don't get Consent to the permissions requested screen like yours

this is due to reusing existing screenshots of SingleTenant or MultiTenant docs. Could maybe be removed.
