### ISSUE TITLE
Wrong access token required claims

### ISSUE THREAD

**Issue by stapetro** [Intility/fastapi-azure-auth#137]
**Describe the bug**
I updated from 4.0.0 to 4.1.1 version and hit an issue regarding the following token claims - **aio**, **uti**, **rh**. They are required in ```fastapi_azure_auth.user.Claims``` class but according to [Azure AD doc](https://learn.microsoft.com/en-us/azure/active-directory/develop/access-token-claims-reference) they are optional.

**To Reproduce**
Here's an example jwt token body from my infrastructure:
```json
{
  "tid": "**dummy-tid**",
  "name": "Stanislav Petrov",
  "idp": "https://login.microsoftonline.com/***/v2.0",
  "sub": "**dummy-sub**",
  "oid": "**dummy-sub**",
  "tfp": "***",
  "nonce": "***",
  "scp": "**dummy-scp**",
  "azp": "**dummy-azp**",
  "ver": "1.0",
  "iat": 1687507633,
  "aud": "**dummy-aud**",
  "exp": 1687511233,
  "iss": "https://***.b2clogin.com/***/v2.0/",
  "nbf": 1687507633
}
```
1. Instantiate ```fastapi_azure_auth.user.User``` class with the example token body above.

**Stack trace**
```shell
Unable to process jwt token. Uncaught error: 3 validation errors for User
aio
  field required (type=value_error.missing)
uti
  field required (type=value_error.missing)
rh
  field required (type=value_error.missing)
Traceback (most recent call last):
  File "C:\***\Lib\site-packages\fastapi_azure_auth\auth.py", line 208, in __call__
    user: User = User(
                 ^^^^^
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 3 validation errors for User
aio
  field required (type=value_error.missing)
uti
  field required (type=value_error.missing)
rh
  field required (type=value_error.missing)
```

**Your configuration**
I'm in the **single tenant** case (_fastapi_azure_auth.auth.SingleTenantAzureAuthorizationCodeBearer_).

**Comment by JonasKs** [comment]
Thank you! Pull request welcome.

**Comment by JonasKs** [comment]
[New release](https://github.com/Intility/fastapi-azure-auth/releases/tag/4.1.2) out. Thanks for the bug report 😊
