### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by mk53202** [Intility/fastapi-azure-auth#147]
**Describe the feature you'd like**
I know it's out of the scope of this project, but wondering if anyone has any examples of using this API with Vue.js or React frontend. Any pointers are appreciated and I think other may be wondering the same.

**Additional context**
Just wondering how to consume the user and role data into a frontend API

**Comment by JonasKs** [comment]
Hi,
There’s a few examples in #73 😊 

Just set up your react app like you did the OpenAPI app, and use the official MSAL library.
