### ISSUE TITLE
Validating extension attributes for managing user roles in B2C

### ISSUE THREAD

**Issue by davidhuser** [Intility/fastapi-azure-auth#148]
This feature request is about potential package support for validating B2C Extension Attributes on the User schema.

As it turns out, B2C does not have roles built-in as Azure AD (as described e.g. [here](https://feedback.azure.com/d365community/idea/88961977-b025-ec11-b6e6-000d3a4f0789)). 

A workaround (or the core feature, depending who to ask) is to use [extension attributes](https://learn.microsoft.com/en-us/azure/active-directory-b2c/user-flow-custom-attributes?pivots=b2c-user-flow#manage-extension-attributes-through-microsoft-graph) through the Microsoft Graph, e.g. as described in [this blog post](https://www.clintmcmahon.com/add-role-claims-to-an-azure-b2c-user-flow-access-token/).

At the moment I am validating the property post-validation (Pydantic). I could subclass the `fastapi_azure_auth.user.User` class in my application but I was thinking whether it could use support in this library.

What are your thoughts on this?

Thank you

**Comment by JonasKs** [comment]
Hi! I didn’t know that (never used B2C really, so the B2C support is mainly through other contributors). 

I would love to add native support. Do you have any particular implementation in mind? Maybe it’s time to investigate having two different User classes, and return a user based on the type of Azure AD one is using.

**Comment by davidhuser** [comment]
Hi, after working with it for a bit I'm not sure I can see the benefit yet. For reference, I'm validating whether a user is an admin in this dependency:

```python

# the B2C extension attribute
CUSTOM_CLAIM = f"extension_{settings.B2C_EXTENSION_APP_ID.replace('-', '')}_Administrator"

async def is_admin(user: Optional[User] = Security(azure_scheme)) -> None:
    if user:
        if not (user.claims.get(CUSTOM_CLAIM, False)):
            raise HTTPException(status_code=403, detail='Admin privileges required')
    else:
        raise HTTPException(status_code=401, detail='Unauthorized')
```

This means I'd need to set the custom claim value externally, i.e. through the `user` endpoint of the Microsoft Graph API.

From my side feel free to close the issue.

**Comment by JonasKs** [comment]
Gotcha. Thanks for the follow-up 😊
