### ISSUE TITLE
Multiple Scopes

### ISSUE THREAD

**Issue by slothary** [Intility/fastapi-azure-auth#149]
**Describe the bug**
I can not specify more then one scope.

**To Reproduce**

```
#works:
azure_scheme = MultiTenantAzureAuthorizationCodeBearer(
    app_client_id=settings.APP_CLIENT_ID,
    scopes={
        f'api://{settings.APP_CLIENT_ID}/user_impersonation': 'Access API as a user'
    },
    validate_iss=True, # has to be true if tendand has to be validated. Validation is in _auth.py
    iss_callable=tendandIsValid
)

#works not (added just the graph.microsoft line):
azure_scheme = MultiTenantAzureAuthorizationCodeBearer(
    app_client_id=settings.APP_CLIENT_ID,
    scopes={
        f'api://{settings.APP_CLIENT_ID}/user_impersonation': 'Access API as a user',
        'https://graph.microsoft.com/User.Read': 'User.Read'
    },
    validate_iss=True, # has to be true if tendand has to be validated. Validation is in _auth.py
    iss_callable=tendandIsValid
)
```

**Error**
auth errorError: Bad Request, error: invalid_request, description: AADSTS28003: Provided value for the input parameter scope cannot be empty when requesting an access token using the provided authorization code. Please specify a valid scope.

In the api permission I have Microsoft Graph User.Read and admin content is given.

Can someone help me to add more then one scope?
In the Microsoft Documentation, Scopes are divided with a Space. But MultiTenantAzureAuthorizationCodeBearer scopes require a dictionary.

Maybe what I try to achieve:

I would like to login the user. Then I get the access token. with that access token, I want to use:

`from azure.identity import OnBehalfOfCredential
credential = OnBehalfOfCredential(
            tenant_id="<Tid>",
            client_id="<cid>",
            client_secret="<secret>",
            user_assertion=userInfo.get("access_token"),
        )
graph_access_token = credential.get_token("https://graph.microsoft.com/user.read+offline_access")
`

with the graph_access_token, I then would like to call the graph api

**Comment by slothary** [comment]
I found the error myself. You cannot mix the scopes. If I use user_impersonation works, when I user User.Read, it works (though the access token cannot be validated). Both together resulting in the Error AADSTS28003.

**Comment by slothary** [comment]
I found that out myself as it looks like (for people who searching for that):

`
from azure.identity import OnBehalfOfCredential

@msGraphRouter.get("/myProfile/get",
        operation_id='myProfile',
        response_class=JSONResponse,
        status_code=status.HTTP_200_OK,
        summary="myProfile()",
        description = "gets my profile from ms graph api.",
        responses= {
            200: {
                "description": "ok",
                "content": {
                    "application/json": {
                        "example":{
                            "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users/$entity",
                            "businessPhones": [],
                            "displayName": "string",
                            "givenName": "string",
                            "jobTitle": "string",
                            "mail": "string",
                            "mobilePhone": "string",
                            "officeLocation": "string",
                            "preferredLanguage": "string",
                            "surname": "string",
                            "userPrincipalName": "string",
                            "id": "uid"
                            }
                    }
                }
            },
            401: {
                "description": "Unauthorized - User not logged in. | Tendand is not known. | User is not registred (my costume function).",
                "content": {
                    "application/json": {
                        "example":{
                            "detail": "Not authenticated"
                        }
                    }
                }
            }
        },
        dependencies=[Depends(azure_scheme)]
        )
async def myProfile (
        user: User = Depends(azure_scheme)
    ):
    userInfo = user.dict()
    credential = OnBehalfOfCredential(
        tenant_id=userInfo.get("tid"),
        client_id=os.getenv("AZURE_APP_CLIENT_ID"),
        client_secret=os.getenv("AZURE_APP_CLIENT_SECRET"),
        user_assertion=userInfo.get("access_token"),
    )
    
    token_request = credential.get_token("https://graph.microsoft.com/profile")
    token = token_request.token
    credential.close()

    url = f"https://graph.microsoft.com/v1.0/me"
    headers = {
        "Authorization": f"Bearer {token}",
    }
    response = requests.get(url, headers=headers)
    return response.json()`

**Comment by JonasKs** [comment]
Glad you figured it out 😊
