### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by michel7x** [Intility/fastapi-azure-auth#164]
I implemented the single tenant application successfully with the library. It is working in the docs properly, but there is not clear how I have to use the API by a client, I mean like CURL. In the docs is integrated perfectly the authentication with my user from my company, when I click auth it redirects me to the login portal. But this workflow is not explained for client usage without the Docs UI. My question is how it is supposed I have to authenticate a user that requesting this from a client (CURL).

For example, the auth flow will be like:
1. CURL request to ${URL}/authenticate
2. Then I will be redirected to Microsoft Login page
3. When enter my user and password this will response to my client with a token for my  user.
4. I can request to my other API endpoints using a Bearer token, because I have it.

This usage is not clear in the docs and I'm still trying to understand how to do it.

**Comment by michel7x** [comment]
Also I found a similar question here: https://stackoverflow.com/questions/74029012/fastapi-fetch-user-and-token-from-azure

**Comment by JonasKs** [comment]
It's documented and answered here: https://intility.github.io/fastapi-azure-auth/usage-and-faq/calling_your_apis_from_python

**Comment by michel7x** [comment]
> It's documented and answered here: https://intility.github.io/fastapi-azure-auth/usage-and-faq/calling_your_apis_from_python

Yes, I tried this, I'm getting a token, but as far as I understand this token is for the client app, isn't? I mean, any member of my organization are signing in. I'm not sure, can be a missunderstanding from my side how the workflow is working, but I'm expecting to call the script and be redirected to the Microsoft login page. It is only returning the token, how I know that this token belongs to me?

```bash
python client.py 
<Response [200 OK]>
eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjlHbW55RlBraGMzaE91UjIybXZTdmduTG83WSJ9.eyJhdWQiOiI1OTNiOWU0ZC01NjVkLTRiMWQtOTExMC1iNTRhODA2Y2YyYmEiLCJpc3MiOiJodHRwczovL2xvZ2luLm1pY3Jvc29mdG9ubGluZS5jb20vZGJiNmM1ODktMjNmMi00YTBiLTk1MTgtZTA3NTgxOGU3YjQ1L3YyLjAiLCJpYXQiOjE2OTc4ODkzNDMsIm5iZiI6MTY5Nzg4OTM0MywiZXhwIjoxNjk3ODkzMjQzLCJhaW8iOiJBU1FBMi84VUFBQUFqMmUrZ3dPdU0zeVY5MDZXaGFNSzh2WlJ1dHZOaG41N3lmRkVBU1hIMkE4PSIsImF6cCI6ImQ2MzYzNDA2LWM1YWUtNDgwMi04MWM1LWU3YTg2YTAyNTQzMyIsImF6cGFjciI6IjEiLCJvaWQiOiJkY2Q5N2UzZC0yZjYwLTQ0ZDUtOTQ4NS1hNzNkYTJjOWZjMGEiLCJyaCI6IjAuQVlFQWljVzIyX0lqQzBxVkdPQjFnWTU3UlUyZU8xbGRWaDFMa1JDMVNvQnM4cnFCQUFBLiIsInN1YiI6ImRjZDk3ZTNkLTJmNjAtNDRkNS05NDg1LWE3M2RhMmM5ZmMwYSIsInRpZCI6ImRiYjZjNTg5LTIzZjItNGEwYi05NTE4LWUwNzU4MThlN2I0NSIsInV0aSI6IlNuNHdLbzU4TGs2YUFla01yWWlmQVEiLCJ2ZXIiOiIyLjAifQ.r3fLHf-POLxpd6vkZ5yJT0jCBMTBjQXWH6Qin1u4MvToS6oO5pjSdaWIh_JVttObCiZsY_32PMlmodtFpX42DKf5pVIJBOIluPjHwnlPukxHlovsap7qrk4rSyFAGD20C8ZMMistGQLUe11nOqWaPbA5H28idM1ssrQ-eCYp05ZardmIPX0DeGfbxfFSni6r2Jy8ZojsgGmOGWzd_iaZkWokLSHhwqHAyWj9sw8HOImBpK44Bp9Qam0sxK-UmChaBjMPlA1ObVQHMrVeDTFDXbfyt6CU7PM1XVAcHWQ1AS3gftX2gR4MLuBluhlyYWa7QZagMc54NxiP4TN4q3Q3ZA
```

**Comment by JonasKs** [comment]
I honestly don't understand the question. You can obtain tokens in multiple ways, either by getting one through a user or an application. The docs I linked to auths as an application. 

If you want to have a login page you need to look into this: https://learn.microsoft.com/en-us/azure/developer/python/sdk/authentication-additional-methods

**Comment by michel7x** [comment]
Hi Jonas! I think this information is useful. Sorry to don't explain better, I'm pretty new implementing this security stuff.

I will check this docs.

Thanks for answering!

**Comment by JonasKs** [comment]
I've written a blog post about it [here](https://engineering.intility.com/article/implementing-oauth2-and-openid-connect-in-your-application), might be a good place to start.

Feel free to ask questions and I'll do my best to answer, I just didn't quite get what the question was.
