### ISSUE TITLE
[BUG/Question] Got 'Token contains invalid claims' error for the `single tenant setup example `

### ISSUE THREAD

**Issue by wxp16** [Intility/fastapi-azure-auth#168]
**Describe the bug**

Follow the single tenant setup example [here ](https://intility.github.io/fastapi-azure-auth/single-tenant/azure_setup).
In Azure, I registered two applications: one is `my-awsome-API`, and the other is `my-awsome-API-OpenAPI`. I am able to get bear token using below code
```
azure_response = await client.post(
            url=f'https://login.microsoftonline.com/{TENANT_ID}/oauth2/v2.0/token',
            data={
                'grant_type': 'client_credentials',
                'client_id': OPENAPI_CLIENT_ID,
                'client_secret': CLIENT_SECRET,  # the secret you created
                'scope': f'api://{APP_CLIENT_ID}/.default',
            }
        )
        token = azure_response.json()['access_token']
        my_api_response = await client.get(
            "http://localhost:8000/",
            headers={'Authorization': f'Bearer {token}'},
        )
        print(my_api_response.json())
```
But I got
```
<Response [401 Unauthorized]>
{'detail': 'Token contains invalid claims'}
```

Any clue about this? 
Below are the screenshots of the two applications: 

![image](https://github.com/Intility/fastapi-azure-auth/assets/18211419/04dc790b-a423-4552-93f0-3fd9eee03e4e)

![image](https://github.com/Intility/fastapi-azure-auth/assets/18211419/ae725712-a767-4bf0-b461-f7db792f1a05)

**Comment by JonasKs** [comment]
Probably leeway again. #165   
Please decode a token at jwt.io and post the claims here (you can delete sensitive data such as your name)

**Comment by JonasKs** [comment]
Also, please enable logging. See the troubleshooting guide: https://intility.github.io/fastapi-azure-auth/usage-and-faq/troubleshooting

**Comment by wxp16** [comment]
@JonasKs Sure. 

> Probably leeway again. #165 Please decode a token at jwt.io and post the claims here (you can delete sensitive data such as your name)



> Probably leeway again. #165 Please decode a token at jwt.io and post the claims here (you can delete sensitive data such as your name)

Here is the decoded token: 
![image](https://github.com/Intility/fastapi-azure-auth/assets/18211419/986f81ce-00e8-4cb7-8965-a366302d1c31)

**Comment by wxp16** [comment]
> Probably leeway again. #165 Please decode a token at jwt.io and post the claims here (you can delete sensitive data such as your name)

In particular, I am able to login on the Swagger doc by clicking the lock icon on top right corner. See below screenshot
![image](https://github.com/Intility/fastapi-azure-auth/assets/18211419/625e502a-f0cd-4c32-8860-6c599e6941a2)

Then I click the Execute button on the Swagger doc page 
![image](https://github.com/Intility/fastapi-azure-auth/assets/18211419/99e37a73-aa51-44ee-833d-8ff156fd78b3)

Below is error logs on the server side
```
INFO 2023-10-26 09:41:39,833 fastapi_azure_auth Token contains invalid claims. Invalid audience
INFO:     127.0.0.1:40940 - "GET / HTTP/1.1" 401 Unauthorized
```

**Comment by wxp16** [comment]
> Also, please enable logging and send us the entire stack trace. See the troubleshooting guide: https://intility.github.io/fastapi-azure-auth/usage-and-faq/troubleshooting


In particular, I am able to login on the Swagger doc by clicking the lock icon on top right corner. See below screenshot

![image](https://github.com/Intility/fastapi-azure-auth/assets/18211419/625e502a-f0cd-4c32-8860-6c599e6941a2)

Then I click the Execute button on the Swagger doc page 

![image](https://github.com/Intility/fastapi-azure-auth/assets/18211419/99e37a73-aa51-44ee-833d-8ff156fd78b3)

Below is error logs on the server side
```
INFO 2023-10-26 09:41:39,833 fastapi_azure_auth Token contains invalid claims. Invalid audience
INFO:     127.0.0.1:40940 - "GET / HTTP/1.1" 401 Unauthorized
```

**Comment by JonasKs** [comment]
Invalid audience suggests you're not fetching the token for the backend app. You should verify your .env file has the correct IDs in the correct places.

**Comment by wxp16** [comment]
> Invalid audience suggests you're not fetching the token for the backend app. You should verify your .env file has the correct IDs in the correct places.

Thanks. Fixed. Just my mistakes on my side. Thanks again for your hint.
