### ISSUE TITLE
[Question] Validate bearer token from Angular SPA (Azure AD) in FastAPI

### ISSUE THREAD

**Issue by krannnn** [Intility/fastapi-azure-auth#170]
Jonas thanks for sharing the awesome library, I appreciate the time and effort you put into this and making it available for developers.

I was going through the library and the [documentation](https://intility.github.io/fastapi-azure-auth/single-tenant/azure_setup), and I was able to reproduce the same behaviour.

However, I'm trying to leverage the library for a scenario where I have already implemented an angular SPA as per the [MSFT docs](https://learn.microsoft.com/en-us/entra/identity-platform/tutorial-v2-angular-auth-code) and now I want to secure my FastAPI endpoints by validating the token that I'm passing as part of the header every time I call a FastAPI endpoint from my angular app.

I created 3 registration apps in total (1 for FastAPI backend, 1 for OpenAPI as per the documentation and 1 for Angular frontend).

I'm not sure how to either replace OpenAPI with angular or add it along side OpenAPI.

Can you please provide any pointers?

Appreciate your help.

**Comment by zbitouzakaria** [comment]
Hello ! Have you managed to solve the issue ? I setup my frontend SPA the same way as the OpenAPI docs but I keep stumbling on the same error when the API tries to validate the token issued by my frontend app registration:

```
 Traceback (most recent call last):
   File "/usr/local/lib/python3.11/site-packages/jose/jws.py", line 262, in _verify_signature
     raise JWSSignatureError()
 jose.exceptions.JWSSignatureError

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/usr/local/lib/python3.11/site-packages/jose/jwt.py", line 142, in decode
     payload = jws.verify(token, key, algorithms, verify=verify_signature)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/jose/jws.py", line 73, in verify
     _verify_signature(signing_input, header, signature, key, algorithms)
   File "/usr/local/lib/python3.11/site-packages/jose/jws.py", line 264, in _verify_signature
     raise JWSError("Signature verification failed.")
 jose.exceptions.JWSError: Signature verification failed.

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/usr/local/lib/python3.11/site-packages/fastapi_azure_auth/auth.py", line 210, in __call__
     token = jwt.decode(
             ^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/jose/jwt.py", line 144, in decode
     raise JWTError(e)
 jose.exceptions.JWTError: Signature verification failed.
 ```

**Comment by JonasKs** [comment]
Please read the troubleshooting guide here: https://intility.github.io/fastapi-azure-auth/usage-and-faq/troubleshooting

Also decide the token at jwt.io to see what the claims are (and send them here if possible).

**Comment by rpatten97** [comment]
Hi did you manage to answer this question? I'm having the same issue.

**Comment by JonasKs** [comment]
It’s impossible to help without getting more context. Please attach specific steps you’ve done, debug logs, decoded claims etc.
