### ISSUE TITLE
[BUG/Question] Error calling openid_config.load_config with Httpx 0.25.1

### ISSUE THREAD

**Issue by kevpye-fabdata** [Intility/fastapi-azure-auth#172]
**Describe the bug**
When using httpx 0.25.1 an exception is thrown when calling `openid_config.load_config()` from the B2CMultiTenantAuthorizationCodeBearer. The exception thrown is `AsyncConnectionPool.__init__() got an unexpected keyword argument 'socket_options'`

The bug can be resolved by downgrading httpx to 0.24.1. The same error is described in the stable diffusion webui project which can be found [here](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/13847). I am just including this in case their fix is applicable. 

**To Reproduce**
1. Setup a brand new FastAPI project in a new python environment - following their documentation.
2. Install pydantic-settings `pip install pydantic-settings`
3. Check the correct dependencies are installed - fastapi==0.104.1, pydantic==2.5.1, pydantic-settings==2.1.0, fastapi-azure-auth==4.3.0, httpx==0.25.1
4. If httpx is a different version `pip install -U httpx` (0.25.1 is the latest version at this time)
5. Follow your project documentation for B2C setup, everything is successful until we arrive to this section [fastaspi-azure-auth](https://intility.github.io/fastapi-azure-auth/b2c/fastapi_configuration#add-loading-of-openid-configuration-on-startup)
6. Add the event startup code and run the application
7. Application will not start with the error described - The exception thrown is `AsyncConnectionPool.__init__() got an unexpected keyword argument 'socket_options`

**Your configuration**
Our settings setup is as exactly described in your tutorial / documentation, we have just renamed some variables to be a little clearer for our project. I have confirmed that the openid_config_url loads as expected in the browser.

In main.py

```python
azure_scheme = B2CMultiTenantAuthorizationCodeBearer(
    app_client_id=Envs.AZUREB2C_CLIENTID,
    openid_config_url=Envs.OPENID_CONFIG_URL,
    openapi_authorization_url=Envs.OPENAPI_AUTHORIZATION_URL,
    openapi_token_url=Envs.OPENAPI_TOKEN_URL,
    scopes=Envs.SCOPES,
    validate_iss=False,
)

@app.on_event("startup")
async def load_config() -> None:
    """
    Load OpenID config on startup.
    """
    try:
        await azure_scheme.openid_config.load_config()
    except Exception as ex:
        print(str(ex))
```

**Comment by davidhuser** [comment]
Hi there,

I cannot yet reproduce after following your steps, with `httpx==0.25.1`. Can you add some logging as per [here](https://intility.github.io/fastapi-azure-auth/usage-and-faq/troubleshooting)?

here's the log output when I tried to reproduce your example.

```
python main.py


main.py:103: DeprecationWarning:
        on_event is deprecated, use lifespan event handlers instead.

        Read more about it in the
        [FastAPI docs for Lifespan Events](https://fastapi.tiangolo.com/advanced/events/).

  @app.on_event('startup')
  
INFO:     Will watch for changes in these directories: ['/private/tmp']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [1762] using StatReload
INFO:     Started server process [1764]
INFO:     Waiting for application startup.
DEBUG 2023-11-16 14:18:03,603 fastapi_azure_auth Loading Azure AD OpenID configuration.
INFO 2023-11-16 14:18:03,619 fastapi_azure_auth Fetching OpenID Connect config from https://mytenant.b2clogin.com/mytenant.onmicrosoft.com/B2C_1_signupsignin/v2.0/.well-known/openid-configuration
INFO 2023-11-16 14:18:04,035 fastapi_azure_auth Fetching jwks from https://mytenant.b2clogin.com/mytenant.onmicrosoft.com/b2c_1_mypolicy/discovery/v2.0/keys
DEBUG 2023-11-16 14:18:04,159 fastapi_azure_auth Loading public key from certificate: {'kid': 'xxx', 'nbf': 1493763266, 'use': 'sig', 'kty': 'RSA', 'e': 'AQAB', 'n': 'xxx'}
INFO 2023-11-16 14:18:04,161 fastapi_azure_auth fastapi-azure-auth loaded settings from Azure AD.
INFO 2023-11-16 14:18:04,161 fastapi_azure_auth authorization endpoint: https://mytenant.b2clogin.com/mytenant.onmicrosoft.com/b2c_1_signupsignin/oauth2/v2.0/authorize
INFO 2023-11-16 14:18:04,161 fastapi_azure_auth token endpoint:         https://mytenant.b2clogin.com/mytenant.onmicrosoft.com/b2c_1_signupsignin/oauth2/v2.0/token
INFO 2023-11-16 14:18:04,162 fastapi_azure_auth issuer:                 https://mytenant.b2clogin.com/xxx/v2.0/
INFO:     Application startup complete.
```

You could also try to use [Lifespan events](https://fastapi.tiangolo.com/advanced/events/#lifespan) for loading the config (as the startup events are officially deprecated in FastAPI now).

**Comment by kevpye-fabdata** [comment]
Hi there, thank you for the very fast response - and for the great work on the library.

Here is the output from the logging config setup you linked to when starting up using httpx 0.25.1. I haven't tried with lifespan events yet. Note the application startup complete message is because the startup code call to load_config is wrapped in a try except

```python
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [67347] using WatchFiles
INFO:     Started server process [67351]
INFO:     Waiting for application startup.
DEBUG 2023-11-16 15:19:24,014 fastapi_azure_auth Loading Azure AD OpenID configuration.
ERROR 2023-11-16 15:19:24,023 fastapi_azure_auth Unable to fetch OpenID configuration from Azure AD. Error: AsyncConnectionPool.__init__() got an unexpected keyword argument 'socket_options'
Traceback (most recent call last):
  File "/Users/myuserdir/miniconda3/envs/testauthenv/lib/python3.11/site-packages/fastapi_azure_auth/openid_config.py", line 42, in load_config
    await self._load_openid_config()
  File "/Users/myuserdir/miniconda3/envs/testauthenv/lib/python3.11/site-packages/fastapi_azure_auth/openid_config.py", line 77, in _load_openid_config
    async with AsyncClient(timeout=10) as client:
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/myuserdir/miniconda3/envs/testauthenv/lib/python3.11/site-packages/httpx/_client.py", line 1397, in __init__
    self._transport = self._init_transport(
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/myuserdir/miniconda3/envs/testauthenv/lib/python3.11/site-packages/httpx/_client.py", line 1445, in _init_transport
    return AsyncHTTPTransport(
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/kevinpye/miniconda3/envs/chatbot_api/lib/python3.11/site-packages/httpx/_transports/default.py", line 275, in __init__
    self._pool = httpcore.AsyncConnectionPool(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AsyncConnectionPool.__init__() got an unexpected keyword argument 'socket_options'
INFO:     Application startup complete.
```

**Comment by kevpye-fabdata** [comment]
Hi again, 

I have been doing some further investigation. I updated to lifecycle events but the issue still persisted. After some further debugging It seems like there was an issue on my machine. For some reason, an old version of httpcore - used by httpx was being installed. Once I updated httpcore to the latest version, I could use httpx 0.25.1 and this issue was resolved. I have updated my requirements txt to ensure the correct versions are installed. 

You can close this issue, thank you for your help and again thank you for the work on this package and providing clear documentation.

**Comment by JonasKs** [comment]
Glad you resolved it, and thanks @davidhuser for helping out 😊

I’ll close this issue. 

As a side note, we should fix startup events in favor as lifespan in the docs, though. Totally forgot about that.

**Comment by justinokay** [comment]
Thanks @kevpye-fabdata downgrading httpx to 0.25.1 resolved this for me!
