### ISSUE TITLE
Adding new fields for Client Secret JWT

### ISSUE THREAD

**Issue by PedroSchroeder** [Intility/fastapi-azure-auth#176]
Hi!
I'm integrating Microsoft ID authentication into my API (api0) and plan to access it using two different APIs (api1 and api2). For this, I'm utilizing a unique Client Secret for each API. However, I'm encountering a challenge: there isn't a field in the generated JWT token (created with the Client Secret) that indicates which API is making the request to api0. I would like to add a custom field to the JWT token to identify the originating API. Those are the default fields in the JWT:

```
{
  "aud": "",
  "iss": "",
  "iat": 1,
  "nbf": 1,
  "exp": 1,
  "aio": "",
  "azp": "",
  "azpacr": "",
  "oid": "",
  "rh": "",
  "sub": "",
  "tid": "",
  "uti": "",
  "ver": "2.0"
}


```

**Comment by JonasKs** [comment]
The `iss` will contain information on who issues the token. The `aud` will contain who the token is intended for.
