### ISSUE TITLE
[Feature request] Support WebSocket connections.

### ISSUE THREAD

**Issue by epelaez1** [Intility/fastapi-azure-auth#191]
Hello! 
First of all thank you for this repo! It has saved me a lot of time. 

I have tried to use `SingleTenantAzureAuthorizationCodeBearer` with a web socket connection and FastAPI throws this error:

`TypeError: AzureAuthorizationCodeBearerBase.__call__() missing 1 required positional argument: 'request'`

I think it would be very easy to add support to WebSockets, just replacing the dependency type from `starlette.requests.Request` to `starlette.requests.HTTPConnection`. 

As described in [documentation](https://fastapi.tiangolo.com/reference/websockets/):

> When you want to define dependencies that should be compatible with both HTTP and WebSockets, you can define a parameter that takes an HTTPConnection instead of a Request or a WebSocket.

I tried a quick patch replacing it in `AzureAuthorizationCodeBearerBase.__call__` and in `OAuth2AuthorizationCodeBearer.__call__`, and it worked perfectly. 

`HTTPConnection` is the base class for both `WebSocket` and `Request`, and it has the `headers` and `state` properties, so it would probably be backwards compatible. 

Let me know if you think it is feasible! If you need hands on, I can try to do a PR.

**Comment by JonasKs** [comment]
Hi! 
I'd love to get a PR for this. Let me know if I can help.

**Comment by sreenivasulureddysura** [comment]
@JonasKs any update on this?

**Comment by JonasKs** [comment]
No, not really.

Any contribution would help, whether it's a test, reproducible example or a full implementation.

**Comment by JonasKs** [comment]
Implemented in #200, please check it out.
