### ISSUE TITLE
Empty raise

### ISSUE THREAD

**Issue by stan-w** [Intility/fastapi-azure-auth#192]
First of all, thanks for the repo! Safes a lot of time.

On https://github.com/Intility/fastapi-azure-auth/blob/1765e70275fc19786e78b1ad64886c50747ef1ea/fastapi_azure_auth/auth.py#L236 there is only a `raise`. Is this intended or should an `InvalidAuth` be raised?

**Comment by JonasKs** [comment]
You’re right - PR welcome! 😊

**Comment by JonasKs** [comment]
I've fixed this in #200.
