### ISSUE TITLE
[Question] Add scopes to redoc and swagger?

### ISSUE THREAD

**Issue by mattias-de-coninck-ad** [Intility/fastapi-azure-auth#196]
To programmatically access FastAPI the OAuth 2.0 client credential flow is used in order to get a token for making requests to the app. In line with the documentation (https://intility.github.io/fastapi-azure-auth/usage-and-faq/calling_your_apis_from_python
) the application should be called using the following scope: `api://{settings.APP_CLIENT_ID}/.default`. However when viewing both the swagger and redoc documentation it seems to indicate that the `api://{settings.APP_CLIENT_ID}/user_impersonation` scopes needs to be used. Is there any way that we can modify this behaviour?

![image](https://github.com/Intility/fastapi-azure-auth/assets/101272552/3a01764a-3a64-4124-9b7e-f39fdf2e3a29)

**Comment by JonasKs** [comment]
You chose what scopes should be available yourself. See example [here](https://github.com/Intility/fastapi-azure-auth/blob/main/demo_project/api/dependencies.py#L22)
