### ISSUE TITLE
[BUG/Question] Scopes are not being validated

### ISSUE THREAD

**Issue by LD250** [Intility/fastapi-azure-auth#197]
**Describe the bug**

Scopes are not being validated

**To Reproduce**

1. follow this docs: https://intility.github.io/fastapi-azure-auth/single-tenant/fastapi_configuration
2. But input a random string as a scope name

```
    @computed_field
    @property
    def SCOPE_NAME(self) -> str:
        return f'api://{self.APP_CLIENT_ID}/random_string'
```

4. Token validation still works

Basically scope only matters for the OpenAPI application. 

It does not matter what scope you pass in `SingleTenantAzureAuthorizationCodeBearer`, it will not be validated

**Comment by JonasKs** [comment]
Using [this](https://intility.github.io/fastapi-azure-auth/single-tenant/fastapi_configuration/#last-thing), as written on the bottom of that page?

**Comment by LD250** [comment]
when I use `scopes` like this
`@app.get("/", dependencies=[Security(azure_scheme, scopes=['wrong_scope'])])`

scope validation works.

I guess my question is, why do I want to specify a scope inside the `SingleTenantAzureAuthorizationCodeBearer` when I do token validation? 

```
azure_scheme = SingleTenantAzureAuthorizationCodeBearer(
    app_client_id=settings.APP_CLIENT_ID,
    tenant_id=settings.TENANT_ID,
    scopes="api://why_do_i_need_this",
)
```

I tried to put arbitrary values there and did not notice any difference. What am I missing?

**Comment by JonasKs** [comment]
Yeah, that scope is only needed in order to enable OpenAPI docs to have checkboxes for which scope to use when authenticating. 

In order to validate on scopes, the Security dependency must be used. This is a FastAPI design choice, nothing I decided myself.

**Comment by LD250** [comment]
Thank you for the explanation, Jonas. 

The project is great, documentation helped me figure out how Entra ID works. Thanks again.
