### ISSUE TITLE
[BUG/Guest User Evaluation]

### ISSUE THREAD

**Issue by yksnilowyrahcaz** [Intility/fastapi-azure-auth#203]
**Describe the bug**

It appears that the `is_guest` function in utils.py evaluates to True even when the "acct" claim evaluates to 0, where 0 indicates that the user is a tenant member and 1 indicates that the user is a guest. Here is the function for reference:

```python
def is_guest(claims: Dict[str, Any]) -> bool:
    """
    Check if the user is a guest user
    """
    # if the user has set up `acct` claim in Azure, that's most efficient. 0 = tenant member, 1 = guest
    if claims.get('acct') == 1:
        return True
    # formula: idp exist and idp != iss: guest user
    claims_iss: str = claims.get('iss', '')
    idp: str = claims.get('idp', claims_iss)
    return idp != claims_iss
```

According to the [Access token claims reference](https://learn.microsoft.com/en-us/entra/identity-platform/access-token-claims-reference), the `idp` "Records the identity provider that authenticated the subject of the token. This value is identical to the value of the Issuer claim unless the user account isn't in the same tenant as the issuer, such as guests. Use the value of iss if the claim isn't present. For personal accounts being used in an organizational context (for instance, a personal account invited to a Microsoft Entra tenant), the idp claim may be 'live.com' or an STS URI containing the Microsoft account tenant 9188040d-6c67-4c5b-b112-36a304b66dad."

In my case, I am using a personal Azure account created for testing and I have assigned myself to both the client and API applications. The access token obtained includes the following claims:
 "iss": "https://login.microsoftonline.com/MY_TENANT_ID/v2.0"
"idp": "live.com"
"acct": 0

The expected behavior is that as a tenant member assigned to the app, I would not evaluate to "guest" user. Is this assumption correct? Would it make sense to check `if claims.get('acct') == 0` as well?

**To Reproduce**

To reproduce this behavior, create an Azure Active Directory (Microsoft Entra ID) instance and add a user to it. Follow the [Azure configuration](https://intility.github.io/fastapi-azure-auth/single-tenant/azure_setup) and [FastAPI configuration](https://intility.github.io/fastapi-azure-auth/single-tenant/fastapi_configuration) examples from the [FastAPI-Azure-Auth](https://intility.github.io/fastapi-azure-auth/) docs to set up the OpenAPI docs and API configurations. Assign the user to the enterprise apps as described in the [user assignment required section of the Guest User docs](https://intility.github.io/fastapi-azure-auth/usage-and-faq/guest_users#user-assignment-required). Run the app and try authenticating and testing the endpoint in the OpenAPI docs.

**Stack trace**

Not applicable. Response consists of `{"detail": "Guest users not allowed"}`

**Your configuration**

I am using the [Azure configuration](https://intility.github.io/fastapi-azure-auth/single-tenant/azure_setup) and [FastAPI configuration](https://intility.github.io/fastapi-azure-auth/single-tenant/fastapi_configuration) from the [FastAPI-Azure-Auth](https://intility.github.io/fastapi-azure-auth/) docs.

**Comment by JonasKs** [comment]
We consider personal accounts invited to a tenant for guest users. This is very much intended from my side.   
All tests can be found [here](https://github.com/Intility/fastapi-azure-auth/blob/main/tests/test_user.py). 

If you'd like to allow for personal users, you should: 
- allow guest users 
- create a new dependency, and only check for acct claims:
```python 
def `deny_guest(user: Annotaded[User, azure_scheme):
    if claims.get('acct') == 1:
        raise InvalidAuthHTTP(detail="guest user not allowed")
    return user
```
Written on phone, might have some syntax errors. 

Please also see #201

**Comment by JonasKs** [comment]
I'll close this, but I still get notified of any comments.

**Comment by yksnilowyrahcaz** [comment]
Hi @JonasKs

Thank you for reviewing my question, for your prompt response, and for your work on this project. I am confused why my user would be considered a guest, considering that it is listed as a tenant member, but I think I just need additional clarification. I do notice that when I run the single tenant example referenced above using my admin user, it works and the API response is `{"message": "Hello World"}` from the OpenAPI docs as SPA. So perhaps when I created my Azure Active Directory (Microsoft Entra ID) instance, I did so as an admin role and invited another personal account of mine to be a member.

**Comment by JonasKs** [comment]
Hi @yksnilowyrahcaz, this is more of a general decision - a personal user isn't a company user (e.g. `<name>@intility.no`), and that's why we consider it a guest account. You're allowed to disagree, but in general, for bigger companies this is true. 

I want users of this library to be extra protected by default, and opt out, instead of having a potential security flaw without knowing.  
I can assure you there is _plenty_ of APIs in the world which unintentionally allow guest users to use them, and Azure themselves had a security incident because of it a year or so ago.
