### ISSUE TITLE
[Question] Where is the OpenAPI docs access token stored?

### ISSUE THREAD

**Issue by yksnilowyrahcaz** [Intility/fastapi-azure-auth#204]
**Describe the question**

Following the [Azure configuration](https://intility.github.io/fastapi-azure-auth/single-tenant/azure_setup) and [FastAPI configuration](https://intility.github.io/fastapi-azure-auth/single-tenant/fastapi_configuration) examples from the [FastAPI-Azure-Auth](https://intility.github.io/fastapi-azure-auth/) docs, where does the access token get stored for it to be used as a bearer token in the authorization header in requests from the OpenAPI docs? Upon inspection of the page, it does not appear to be in local storage, session storage, or cookies. There does appear to be a cookie set called "ajs_anonymous_id" with a uuid as the value. Perhaps this uuid is a key to a server-side cache containing the access token as the corresponding value? I also tried to look for signs of the access token in the swagger-ui-bundle.js file in the frames section of the application section of a page inspection, but it is unclear if it is being called from memory in there or something else.

**To Reproduce**

To reproduce, run the [Azure configuration](https://intility.github.io/fastapi-azure-auth/single-tenant/azure_setup) and [FastAPI configuration](https://intility.github.io/fastapi-azure-auth/single-tenant/fastapi_configuration) examples from the [FastAPI-Azure-Auth](https://intility.github.io/fastapi-azure-auth/) docs.

**Stack trace**

Not applicable.

**Your configuration**

Using the configuration from the [Azure configuration](https://intility.github.io/fastapi-azure-auth/single-tenant/azure_setup) and [FastAPI configuration](https://intility.github.io/fastapi-azure-auth/single-tenant/fastapi_configuration) examples from the [FastAPI-Azure-Auth](https://intility.github.io/fastapi-azure-auth/) docs.

**Comment by JonasKs** [comment]
Hi, 

This question is probably best asked at the swagger GitHub repo, but as far as I know, it’s not stored anywhere persistent (e.g. in LocalStore), but rather in a normal JS variable, which is why a simple page refresh require a new login.

**Comment by yksnilowyrahcaz** [comment]
Hi @JonasKs

Thank you for your response to my question. I suppose you are right, this question is more appropriately posed at the swagger Github repo.

For what it is worth, I'll confirm that the access token is stored in a JS variable called `swaggerUIRedirectOauth2.auth.token.access_token` that is defined when auth code flows succeed. It can be accessed in the browser console. The `swaggerUIRedirectOauth2` object also contains other information related to OAuth2.

**Comment by JonasKs** [comment]
Awesome, thanks for letting me know 😊
