### ISSUE TITLE
[Documentation - Locking Down on Roles ]

### ISSUE THREAD

**Issue by DuncBegg** [Intility/fastapi-azure-auth#205]
**Describe the feature you'd like**

Under the documentation section "Locking Down on Roles" could you please clarify whether the Azure set up is for the registered webapi or for some sort of registered client app that talks to the api? 
I am guessing the latter since the Single-tenant Setup has the webapi registered as 'my-awesome-api' where as the registered app in the "Locking Down on Roles" section is called FastAD. 

**Additional context**

**Comment by JonasKs** [comment]
Yeah, sorry, that doc was taken from #117. 

Your role should be in the backend appreg.

**Comment by JonasKs** [comment]
I'm closing this, as I have no intention to update the docs with new pictures, but PR welcome.
