### ISSUE TITLE
[BUG/Question] Python 3.9 still supported?

### ISSUE THREAD

**Issue by ndxmrb** [Intility/fastapi-azure-auth#208]
Hi there,

Using the new version 5.0.0 in conjunction Python 3.9, we get a TypeError in `exceptions.py` due to `unsupported operand type(s) for |: 'type' and 'type'`. This is due to using the new typing syntax with `|` instead of `Union[...]`. 

Is 3.9 still supposed to work? My first impression was yes, because e.g. `Optional[...]` instead of `SomeType | None` is used in the codebase, but then again that's probably not indicating much.
- If 3.9 is still supported, `Union[...]` could be used. Alternatively, `from __future__ import annotations` enables the use of `|` in typing
- If it's not supported anymore, the Python requirement in `pyproject.toml` should be updated to reflect that. 

I didn't create a PR as I wasn't sure which of the options above it should be...

Thanks for this package, it really makes security approachable! 🚀

**Comment by JonasKs** [comment]
Hi, that's unintentional. PR welcome! 😊

**Comment by JonasKs** [comment]
Oh, about the options, I'd prefer `from __future__ import annotations` personally 😊

**Comment by ndxmrb** [comment]
I preferred that, too 😋 

I created a PR. Maybe 3.9 and 3.10 should be added to the matrix in GitHub workflows, too?
