### ISSUE TITLE
[Docs] Update docs to reflect new Entra ID Application Registration manifest format

### ISSUE THREAD

**Issue by MrR0bert** [Intility/fastapi-azure-auth#211]
**Describe the bug**
In two months time (December 2nd, 2024) Microsoft will disable the ability to modify the current "AAD Graph App Manifest" in favor of the new "Microsoft Graph App Manifest" format.

The documentation on the setup of three scenarios (Single Tenant, Multi Tenant and B2C) currently depicts the use of the "old" manifest format (in the steps were the `accessTokenAcceptedVersion` should be modified from `null` to `2`.

In the new format, this property has been renamed and moved to a different location in the manifest. It used to be called `accessTokenAcceptedVersion` and located in the root of the manifest. In the new format it called `requestedAccessTokenVersion` and is located in the `api` node.

**To Reproduce**
N/A

**Stack trace**
N/A

**Your configuration**
N/A

**Comment by MrR0bert** [comment]
I'll do my best 😁

**Comment by dansmachina** [comment]
Hi! I took the liberty of creating a PR with some basic changes to the docs: https://github.com/Intility/fastapi-azure-auth/pull/212. Please feel free to contribute if more is needed :) 

Awesome library btw, we are using it a lot in our projects ❤️

**Comment by MrR0bert** [comment]
> Hi! I took the liberty of creating a PR with some basic changes to the docs: #212. Please feel free to contribute if more is needed :)
> 
> Awesome library btw, we are using it a lot in our projects ❤️

Thanks, I haven't had much time to do this yet
