### ISSUE TITLE
[BUG/Question] Proof Key for Code Exchange is required for cross-origin authorization code redemption

### ISSUE THREAD

**Issue by tsegato** [intility/fastapi-azure-auth#221]
**Describe the bug**

I have followed the step by step guide directly as is: https://intility.github.io/fastapi-azure-auth/
Everything is setup as described. As far as I can see its related to the reply urls. But those are added too.

![image](https://github.com/user-attachments/assets/12d7149d-33f3-44ee-9374-3ec4a4b1605e)

However I get following error when trying to Authorize:
AADSTS9002325: Proof Key for Code Exchange is required for cross-origin authorization code redemption.

**Comment by JonasKs** [comment]
Sounds like you're browsing your app on `127.0.0.1` instead of `localhost`?

**Comment by JonasKs** [comment]
Stale, closing. I’ll be notified if you respond. 😊
