### ISSUE TITLE
[Question] Integration with React Native

### ISSUE THREAD

**Issue by yeguacelestial** [Intility/fastapi-azure-auth#24]
Hello, I followed the docs. Everything is well written, and this is probably the best auth library I've seen for FastAPI.

However, I got lost in the woods of FARM stack. How can this library be integrated with a React Native front-end? What flow should one follow? Been lurking around but it seems like a quite uncommon use case.

**Comment by JonasKs** [comment]
Hi! Thank you for the kind words. 😊 

Any flow fetching a token would work. Preferably client side applications should use the Authorization Code (using PKCE) flow. That’s the flow the OpenAPI docs also use.   

I’m not a frontend developer so I’ll tag @h3rmanj, he might be able to correct me if the following is wrong:  

You can use the Microsoft MSAL react package to handle all token fetching in react. You should set up your react application like you did for your OpenAPI docs in Azure AD. [This tutorial](https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-react) seem to use the correct flow and libraries.

Quote from the [msal-react GitHub](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-react) README:

> This version of the library uses the OAuth 2.0 Authorization Code Flow with PKCE.

**Comment by h3rmanj** [comment]
I don't really have any experience with React Native, and I don't really know if Microsoft's `msal` packages are Native friendly. I'm assuming they are not as they probably relies heavily on browser APIs and the DOM, but I might be wrong. [`react-native-msal`](https://github.com/stashenergy/react-native-msal) might be an alternative? As Jonas said you should still use the Authorization Code Flow with PKCE.

**Comment by JonasKs** [comment]
Seems like there's some specific examples on the PKCE flow on the [official website](https://reactnative.dev/docs/0.62/security#oauth2-and-redirects), using [this library](https://github.com/FormidableLabs/react-native-app-auth). An example can be found [here](https://github.com/FormidableLabs/react-native-app-auth/blob/main/docs/config-examples/azure-active-directory.md#v2). 

Good luck! 🚀

**Comment by JonasKs** [comment]
@yeguacelestial I believe we’ve answered your question as best as we can, so I’m going to close this issue. 

Feel free to re-open if you have any more questions.
