### ISSUE TITLE
Cryptography package changed hazmat primitives [BUG/Question]

### ISSUE THREAD

**Issue by bmoore** [Intility/fastapi-azure-auth#25]
**Describe the bug**
If using this package with the most recent version of cryptography, apps crash due to a change in the hazmat primitives.

**To Reproduce**
Have the following requirements

fastapi[all]
fastapi-azure-auth
uvicorn
pytest

1. pip install --no-cache-dir -r requirements.txt
2. Run the sample "getting started" app `uvicorn app:app --reload`

**Stack trace**
...
    from fastapi_azure_auth import SingleTenantAzureAuthorizationCodeBearer
  File "/home/vcap/deps/0/python/lib/python3.9/site-packages/fastapi_azure_auth/__init__.py", line 1, in <module>
    from fastapi_azure_auth.auth import (  # noqa: F401
  File "/home/vcap/deps/0/python/lib/python3.9/site-packages/fastapi_azure_auth/auth.py", line 14, in <module>
    from fastapi_azure_auth.openid_config import OpenIdConfig
  File "/home/vcap/deps/0/python/lib/python3.9/site-packages/fastapi_azure_auth/openid_config.py", line 7, in <module>
    from cryptography.hazmat._types import _PUBLIC_KEY_TYPES as KeyTypes
ModuleNotFoundError: No module named 'cryptography.hazmat._types'

**Your configuration**
Python 3.9.6
using venv

**Comment by bmoore** [comment]
https://github.com/Intility/fastapi-azure-auth/pull/26

**Comment by JonasKs** [comment]
Hi👋 Thank you for the report and pull request!   
I will have a look tonight.

**Comment by bmoore** [comment]
Thanks. I updated the toml to point to cryptography 35.0.0 that was released on Wednesday.
