### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by alexjolig** [Intility/fastapi-azure-auth#36]
Hi,
I'm using this library. everything works fine when I dockerize my app and run the docker image. But if I try to run my project locally, I get this error:

`RuntimeError: Unable to fetch provider information. Cannot connect to host login.microsoftonline.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')]`

How come it works when running via docker image locally, but not without it? The only difference I can see is that image is running on **Linux** while locally I'm using **MacOS**.  Can you please guide me how to solve this?
Also sorry if I'm asking this here, I couldn't find a solution out there!

**Comment by JonasKs** [comment]
Hello! Happy it works well for you (well, in Docker😅)!

Sounds like your local Python installation don’t have public certificates installed. How did you install Python?

@ingvaldlorentzen might give a little hint on how it could be resolved, but unfortunately I’m not a Mac user.

Could you try some of the tricks described in this [SO thread](https://stackoverflow.com/questions/42098126/mac-osx-python-ssl-sslerror-ssl-certificate-verify-failed-certificate-verify)?

**Comment by alexjolig** [comment]
Thanks for the reply. I tried it before with `pip install -U certifi` didn't help. But installing through **Applications** seems to work. but now I'm getting another error:

`Unable to fetch OpenID configuration from Azure AD. Error: 400, message='Bad Request', url=URL('https://login.microsoftonline.com/3/v2.0/.well-known/openid-configuration')`

The error is from this module:

```
File "/venv/lib/python3.9/site-packages/fastapi_azure_auth/openid_config.py", line 55, in load_config
    raise RuntimeError(f'Unable to fetch provider information. {error}')
```

**Comment by JonasKs** [comment]
The `3` in that URL should be the entire tenant ID. The URL should also work directly in the browser.
```
https://login.microsoftonline.com/3/v2.0/.well-known/openid-configuration
                                 ^^ 
                              Tenant ID
```

**Comment by alexjolig** [comment]
Thanks @JonasKs The second error was my bad! I fixed the tenant ID and now it's working.

**Comment by JonasKs** [comment]
Awesome! Happy coding! :rocket:
