### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by alexjolig** [Intility/fastapi-azure-auth#37]
I'm creating an API gateway using fastAPI for some microservices, which in I authenticate user via Azure AD via this library. So I'm trying to take out the user info from the request object (_request.state.user_) and inject my own token in it to later pass to other microservices. I can't do this in middleware, cause user info is getting added after it.
But I tried creating an decorator:

```
from functools import wraps

def token_injector(function):
    @wraps(function)
    def wrap_function(*args, **kwargs):
        user: User = kwargs['request'].state.user
        new_token = generate_token(user)
        kwargs["new_token"] = new_token # or kwargs['request']["new_token"] = new_token
        return function(*args, **kwargs)
    return wrap_function
```

and for this approach, I'm getting these errors:

`ValueError: [TypeError("'coroutine' object is not iterable"), TypeError('vars() argument must have dict attribute')]
`
and

`TypeError: 'Request' object does not support item assignment`

Can you please guide me how did you inject user in request.state, so I can do the same?

**Comment by alexjolig** [comment]
Ok I got a solution, and I've posted [in stackoverflow](https://stackoverflow.com/a/69840207/2263683). But I'm leaving this open to see if there's any better solution for this. If not you can close this question. Thanks.

**Comment by JonasKs** [comment]
Hi! Thank you for following up letting me know it's been resolved.

There are a few questions here, so I'll try to answer them as best as I can.  Let me know if anything is unclear.

First off, I agree with the approach you've landed on. Chaining dependencies is the way to make sure something is "in the right order". It is also the approach I've described in the docs [here](https://intility.github.io/fastapi-azure-auth/single-tenant/locking_down_on_roles). It's also deomonstrated in the demo project, in [this view](https://github.com/Intility/fastapi-azure-auth/blob/main/demo_project/api/api_v1/endpoints/hello_world.py#L18), using [this dependency](https://github.com/Intility/fastapi-azure-auth/blob/main/demo_project/api/dependencies.py#L24-L30). 

The user model is defined [here](https://github.com/Intility/fastapi-azure-auth/blob/main/fastapi_azure_auth/user.py#L6-L13), and is created [here](https://github.com/Intility/fastapi-azure-auth/blob/main/fastapi_azure_auth/auth.py#L186-L187). 

I would recommend you to not "get rid of" the `User` object, but maybe create your own user model and append to it. Here's an example:

```py
from pydantic import Field
from fastapi_azure_auth.user import User
from typing import Optional

class CustomUser(User):
    new_token: Optional[str] = Field(default=None)
```
and then in your own dependency do this:

```py
from fastapi import Depends
from fastapi_azure_auth.auth import InvalidAuth
from fastapi_azure_auth.user import User

async def new_user(user: User = Depends(azure_scheme)) -> None:
    new_token = 'ey....'
    new_user = CustomUser(**user.dict() | {'new_token': new_token})
```

I hope this code runs (I haven't been able to test it), but if not, let me know and I'll write a real example for you tomorrow.

**Comment by alexjolig** [comment]
That was a great advise and explanations. I moved the dependency part to a higher api_router and now it works for all the APIs. Thank you! This answer is gonna help me through the whole project in the future. I really appreciate it.

**Comment by JonasKs** [comment]
I’m happy to hear that 😊 Best of luck!

**Comment by alexjolig** [comment]
Just one small thing need to change in your answer. I had to change the dependency like this for it to work:

```
async def new_user(request: Request) -> None:
    new_token = 'ey....'
    new_user = CustomUser(**request.state.user.dict() | {'new_token': new_token})
    request.state.user = new_user
```

**Comment by JonasKs** [comment]
Ah, yes, I forgot about that part of the question 👍
