### ISSUE TITLE
[QUESTION] Login integration

### ISSUE THREAD

**Issue by productoptimization** [Intility/fastapi-azure-auth#39]
First, thank you for the library it's great!

Would be nice to see a very basic integration between the library and a logging endpoint in order to understand the integration with the library in that process. 

I can logging with the Fastapi docs but not from my app. I feel I'm reinventing the wheel trying to do the authentication steps. I'm ending creating my own functions try to follow the oath2 flow.

Thanks!

**Comment by JonasKs** [comment]
Hi!

> First, thank you for the library it's great!

Thank you! 😊 

> Would be nice to see a very basic integration between the library and a login endpoint in order to understand the integration with the library in that process.

This package _only_ supports **API** auth, using bearer tokens. This means your user must log in without any involvement of the backend and recieve an `access_token`. This token is then sent to the FastAPI backend in the header.

> I can log in with the OpenAPI docs but not from my app. I feel I'm reinventing the wheel trying to do the authentication steps. I'm ending creating my own functions try to follow the oath2 flow.

Login to the frontend will vary on the framework and how the application is written. Are your frontend a single-page application (e.g. react/angular), or are you hosting it through FastAPI (MVC frontend, such as jinja2)? 

(I've edited your questions a tiny bit, since I was a bit confused whether you talked about logging (as in `logger.debug(...)`) or logging in to the application.)

**Comment by JonasKs** [comment]
You're welcome!

I'll try to describe how it works in very short steps (inspired from what I wrote in #33, which I recommend you read):

* Frontend fetches token with the PKCE flow (using e.g. `Azure ADAL` library for react)
* Frontend makes an API call to the FastAPI backend, attaching the `access_token` in the header as a `Bearer` token. 
  * You can see an example on how this works in the OpenAPI documentation when you try out the API
* Backend receives and validates the token, and if everything is OK, the request will be passed on to the API.

I'm closing this issue, but you can still comment (I will still get notified), re open it or create a new issue if you have any further questions. :blush:

**Comment by productoptimization** [comment]
I all ready own you a couple coffees man!
The topic has been more complex than I expected but with your help I think I'll have it done.
Maybe It's good idea to mention the PKCE flow explicitly on the documentation, just to avoid confusion in noobs 
Thanks again!!

**Comment by JonasKs** [comment]
🍻   
I am actually writing a blog post about how OpenID Connect and PKCE works and how they tie together. It will be released soon™️. I'll make sure to link to it in the documentation!😊

**Comment by productoptimization** [comment]
Nice!! I'll be waiting for that post!
See ya  around!!

**Comment by JonasKs** [comment]
I wrote `Azure ADAL` above, but you should use `Azure MSAL`. So if you're using react, please use `MSAL` and not `ADAL`.

**Comment by productoptimization** [comment]
You are killing me with acronyms!....jajaja. I feel like Tarzan here. But here's come google to the rescue.

**Comment by JonasKs** [comment]
If you write your frontend application with react, there is a library developed by Azure that handles everything you need. The library is called [MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-js)

**Comment by JonasKs** [comment]
Hi @productoptimization, @alexjolig and @ yeguacelestial!

I’ve written a little blog post on how everything is glued together. You can read it [here](https://engineering.intility.com/article/implementing-oauth2-and-openid-connect-in-your-application)

**Comment by JonasKs** [comment]
Also @yeguacelestial, see the comment above 😊

**Comment by yeguacelestial** [comment]
@JonasKs yeah definitely PKCE has its learning curve, struggled a little bit understanding what I was doing but essentially I did what you suggested, and it works!

Thank you very much man 😄
