### ISSUE TITLE
[BUG] fastapi-azure-auth is not published to pypi

### ISSUE THREAD

**Issue by hmedhat** [Intility/fastapi-azure-auth#42]
**Describe the bug**
I am unable to install fastapi-azure-auth, everytime I try I get
```
ERROR: Could not find a version that satisfies the requirement fastapi-azure-auth (from versions: none)
ERROR: No matching distribution found for fastapi-azure-auth
```

**To Reproduce**
You can run this command on a plain ubuntu docker container and you will get the same error.
`docker run -it ubuntu /bin/bash -c "apt-get update && apt-get install -y python3 python3-pip && pip install fastapi-azure-auth"`

**Comment by JonasKs** [comment]
Hi, it is. How ever, the requirements is specified [here](https://github.com/Intility/fastapi-azure-auth/blob/main/pyproject.toml#L43-L44). I assume your Python version is 3.8.

**Comment by JonasKs** [comment]
@hmedhat In other words, I'd recommend using a official `python` image instead of a `ubuntu` image.

`docker run -it python:3.10-bullseye` or `python:3.10-slim`. [Docker docs](https://hub.docker.com/_/python).

**Comment by hmedhat** [comment]
Thanks for the quick reply, yeah that seemed to be my issue.
