### ISSUE TITLE
[Documentation]: Suggested update in walkthrough

### ISSUE THREAD

**Issue by bkmetzler** [Intility/fastapi-azure-auth#45]
**Describe the issue**
(https://intility.github.io/fastapi-azure-auth/single-tenant/azure_setup#step-4---allow-openapi-to-talk-to-the-backend)

There should be one final step on this walk through.  Azure has added another section under "Exposing an API" called "Authorized client applications".  If you do not link the OpenAPI back to the original application, the end-user will be prompted to request consent from an administrator.

**To Reproduce**
Manually go through the Single Tenant walkthrough (https://intility.github.io/fastapi-azure-auth/single-tenant/).  Once fully complete, any attempt to log into Azure via OpenAPI will send the end-user to a page, as described below:

![Selection_030](https://user-images.githubusercontent.com/32405329/149384679-0c67fe78-d1e7-445a-b01b-2fcb97498fba.png)

**Fix**
This is so the end-user doesn't see this prompt.
1.) Go to "Expose an API" under your Sample application (not the OpenAPI).
2.) Under "Authorized client applications" click "Add a client application"

![Selection_029](https://user-images.githubusercontent.com/32405329/149385765-97323325-bc63-44c3-986e-2afba7dd61d3.png)

3.) Copy the Application Id from your 'Sample - OpenAPI' into the 'Client ID' field.
4.) Select the exposed 'api://*' check box 
5.) Click "Add Application"

Now when you click "Authorize"/"Login" via SwaggerUI, the end user will no longer require Admin consent.

I hope this helps,
-Brian

**Comment by h3rmanj** [comment]
Hi, while authorized clients will skip consenting, it shouldn't be required.

Did you remember to check that users can consent as well?
![image](https://user-images.githubusercontent.com/11387548/149392059-c86e8a70-ab14-4e2c-bbdc-82571a63991e.jpeg)

**Comment by JonasKs** [comment]
@bkmetzler ? 😊

**Comment by bkmetzler** [comment]
Yes, "Admins and users" is selected.
![Selection_033](https://user-images.githubusercontent.com/32405329/150799141-3668bf42-bb82-4652-8092-4fa5620ced22.png)

**Comment by h3rmanj** [comment]
That's odd. Do you have control of the tenant? The only thing I can think of is that there might be a strict policy in place which don't allow users to consent anyway. I don't really know if that's possible though, but we have never encountered this in our tenant.

We could add a info box guiding the user to set up authorized client applications for the API, if they don't want the user to need to consent. But I don't think it should be a required step, as hitting the admin consent screen is not the normal behavior when user consent is enabled.

**Comment by JonasKs** [comment]
We're unable to reproduce this. Can you share some more information about your setup, @bkmetzler? Do you have `prompt=admin` in the redirect URI to Azure, signing in from a different tenant or something similar?

**Comment by bkmetzler** [comment]
After looking into this, it seems to be a related to the fact I am using an enterprise level tenant with limitations at the tenant level.

There is no "prompt=admin" in the redirect URI.

**Comment by JonasKs** [comment]
Thank you for getting back to us, @bkmetzler!  

I'd like to have a note in the docs which just links to this issue, for those who has issues with admin consent being asked for after following the tutorial. Would you like to create a PR, or should I do it? :blush:

**Comment by JonasKs** [comment]
Thank you so much @bkmetzler. I've added documentation for this [here](https://intility.github.io/fastapi-azure-auth/usage-and-faq/admin_consent_when_logging_in).
