### ISSUE TITLE
[BUG/Question] Is it possible to create a user?

### ISSUE THREAD

**Issue by carlosporta** [Intility/fastapi-azure-auth#60]
I want to create an application with user registration with any email domain, is it possible?

**Comment by JonasKs** [comment]
Hello! This would be possible using an Azure B2C tenant. 

The B2C tokens can be validated using this package (if you use the newest release). Unfortunately, we don’t have any documentation on how to set up a B2C tenant. At the moment only single- and multi-tenant applications have a tutorial. 

But yes, it is possible, but you’ll have to figure out the Azure setup yourself. See #46 #48

**Comment by carlosporta** [comment]
Hello! Thank you, @JonasKs, I will read about it.

**Comment by lsmith77** [comment]
@JonasKs are you looking to add documentation for B2C?

**Comment by JonasKs** [comment]
Hi @lsmith77! 

I'm not an Azure B2C user, but contributions (in a PR or as a comment) are welcome if you do figure it out.

As a side note, I'll be out of office for a week or so, so replies may be slower than usual.
