### ISSUE TITLE
[Documentation] How to access user attributes

### ISSUE THREAD

**Issue by martin-greentrax** [Intility/fastapi-azure-auth#61]
This crucial part is missing in the documentation.
based on: https://github.com/Intility/fastapi-azure-auth/pull/8#issuecomment-899034836

Here a stub that could help:

You can access the authorized user's attributes with `request.state.user`
A sample view that outputs the current user name:
```
from fastapi import Request, Security

@app.get("/hello", dependencies=[Security(azure_scheme)])
async def hello(request: Request):
    return "Hello {}".format(request.state.user.name)
```

**Comment by JonasKs** [comment]
Hi, I agree!

> based on: https://github.com/Intility/fastapi-azure-auth/pull/8#issuecomment-899034836

Hehe, yes, I knew there would be questions back then and then I forgot about it. 

I also got a question about it [here](https://github.com/Intility/fastapi-azure-auth/issues/47#issuecomment-1064224746). 

Would you like to contribute with a pull request? 😊 

We could move these two sites ([1](https://intility.github.io/fastapi-azure-auth/multi-tenant/locking_down_on_roles), [2](https://intility.github.io/fastapi-azure-auth/single-tenant/locking_down_on_roles)) which are equal and then create a new section that's called something like `Usage` which has questions and answers like these?

**Comment by martin-greentrax** [comment]
I'm happy to contribute, I actually tried but currently don't have the time to get familiar with Docusaurus and don't want to mess up the page structure

**Comment by JonasKs** [comment]
No worries. I'll leave this open for someone if they want to contribute for a few days, and if not, I'll do it. Thank you for reminding me!

**Comment by JonasKs** [comment]
I've added documentation [here](https://intility.github.io/fastapi-azure-auth/usage-and-faq/accessing_the_user) and moved the pages as suggested above.

**Comment by martin-greentrax** [comment]
Thank you, @JonasKs 
I m sure it will help people getting on board.

**Comment by JonasKs** [comment]
😊 Also added a bunch of new pages if you'd like to check them out under the same section, such as how to use Graph and how to call your APIs from Python 🎉
