### ISSUE TITLE
[BUG/Question] Minor error in documentation

### ISSUE THREAD

**Issue by Christian-Schultz** [Intility/fastapi-azure-auth#70]
Thank you for this excellent module - and the fantastic documentation. I found a small typo in the section [Calling your APIs from Python
](https://intility.github.io/fastapi-azure-auth/usage-and-faq/calling_your_apis_from_python). It should be 
`'client_id': settings.APP_CLIENT_ID,` and not `'client_id': settings.OPENAPI_CLIENT_ID,`. 

I hope you will continue to maintain this project - it has been a time-saver for me.

**Comment by JonasKs** [comment]
Hi! Thanks for the kind words!

Which client ID you should use will vary from which application you create the secret. 😊 In my example I create the secret for the OpenAPI app reg. I think this example is closer to a real life scenario, where another application would like to authenticate to your API. 

So, if you created your secret in the backend app reg, you have to swap the ClientID to the backend app reg too. 

Hope this cleared up a bit, and thank you so much for creating an issue when you see something that’s off. I’ll try to explain this better in the documentation😊

**Comment by Christian-Schultz** [comment]
I see - I guess it makes sense that it would often be a token granted to another app registration instead of the "root" app registration. What fooled me, was that it was the OpenAPI app registration used as an example instead of an entirely new app registration. I think it would not be usual practice to create tokens through the OpenAPI app registration?

**Comment by JonasKs** [comment]
Ah, yes, agree. I’ll keep this issue and make sure we update it to make it more clear. 

PRs welcome if you’d like to contribute 😊

**Comment by JonasKs** [comment]
I had the project open, so made a PR. I'll happily close it in favor of yours if you're currently making one. 

If not, I'd love a review. 😊

**Comment by Christian-Schultz** [comment]
Thank you for clarifying this - I think it's much better now.
