### ISSUE TITLE
[Feature request] Support for python 3.8+ versions.

### ISSUE THREAD

**Issue by manupatel007** [Intility/fastapi-azure-auth#74]
I had gone through the packages associated with fastapi-azure-auth and found that none of them needs a python version higher then 3.8. And if we can import some of the type hints from typing instead of using inbuilt type hints(as per the [new feature in python 3.9](https://docs.python.org/3/whatsnew/3.9.html#type-hinting-generics-in-standard-collections) and a few other changes, we can serve a bit wider audience with this nice package. Are you open for a PR in this context?

**Comment by JonasKs** [comment]
Hi! Yes, I'd gladly accept a pull request for this! 😊
