### ISSUE TITLE
[Question] - How can I get the refresh token after successful authorization?

### ISSUE THREAD

**Issue by yosi1314** [Intility/fastapi-azure-auth#82]
Hi, I'm trying to gain access to the refresh token after the client clicks authorize.
Is there an option to add an explanation whats going on on the fastapi side once the client clicks authorize?
Also I was wondering if the refresh_token can be added to the User class so I can also implement a token refresh functionality to my app. 
Thanks in advance!

**Comment by JonasKs** [comment]
This module only implements _validation_ of tokens + a login through Swagger/OpenAPI docs using the PKCE Authorization Code flow. The backend will never receive nor handle refresh tokens. In other words, this package only implements Azure AD for Rest APIs.  How your frontend/scripts handle login, token refresh etc. will be up to you. 

You can read about it [here](https://engineering.intility.com/article/implementing-oauth2-and-openid-connect-in-your-application).

**Comment by JonasKs** [comment]
I'm closing this issue, but I will still be notified if your reply. 

Have a good weekend 😊
