### ISSUE TITLE
Make appid/azp claims truely optional

### ISSUE THREAD

**Issue by nickpholden** [Intility/fastapi-azure-auth#86]
Can you please make appid/azp really optional, we handle autherisation/access through the "assignment required" option and so don't want to have to configure the list of app ids inside fastapi too. It would be really good to make it optionally accept any appid in that claim.

**Comment by JonasKs** [comment]
We verify the audience, but not `azp`/`appid`. See [here](https://github.com/Intility/fastapi-azure-auth/blob/main/fastapi_azure_auth/auth.py#L162-L190). 

Even if you disallow guest users, the backend should still validate the audience (as it is now) for the application, ensuring a token hacked for another app cannot be used for this one.
