### ISSUE TITLE
Sign in user via '/login'-endpoint [BUG/Question]

### ISSUE THREAD

**Issue by RasRakaras** [Intility/fastapi-azure-auth#95]
Hi, I am new to AzureAD and the Authentication-flow (and GitHub).
 
I am building an API with SingleTenantAzureAuthorization.
I have implemented user-login via swagger 'authorize'-Button and secured my data-endpoints successfully, as shown in the documentation.

But I would like to provide a '/login' endpoint that redirects the user/client to Azures SSO-page, then have them redirected to another endpoint, say 'localhost:port/webinterface'.

I have no clue how to build the POST Request to "https://login.microsoftonline.com/myTenantId/oauth2/v2.0/authorize" including my Scope, redirect_uri and code_challenge. Is this even possible with using the fastapi_azure_auth-package and the azure-scheme and settings? Or do I have to use msal for that?

**Comment by JonasKs** [comment]
Hi, and welcome 😊

This package only implements authorization of APIs. In practice this means that the backend only handle and validate access tokens, but don't care about how the user get them in the first place. An example is the OpenAPI/Swagger documentation, it is a separate app registration and as far as the backend know, it is a separate, pure frontend application. 

So to answer your question - yes, you should use MSAL to fetch a token from your frontend and send the token to your API. I highly recommend reading #73 and #39 - I probably explained this better there. I've also written a blog post about how these things work behind over at the [engineering@intility blog](https://engineering.intility.com/article/implementing-oauth2-and-openid-connect-in-your-application). 

Hope that answered your question😊

**Comment by RasRakaras** [comment]
Hey,

yes, now I know how to move forward. Thanks for your reply and the references!
