### ISSUE TITLE
[Question] Azure's Authentication feature (Easy Auth)

### ISSUE THREAD

**Issue by Johschmidt43** [Intility/fastapi-azure-auth#97]
Hi, 

this work looks really great! Is this library targeted to those who deploy their fastAPI application somewhere other than on Azure services where [Azure's Easy auth](https://docs.microsoft.com/en-us/azure/app-service/overview-authentication-authorization) cannot be (or is deliberately not) used but MS is the identity provider?

If that's the case, may I suggest to add a reference for people like me that are not security experts and want to deploy their application to a service managed by Azure (azure function, azure web app etc.). I think this would help non-experts to show them their options and help them to decide if the authentication part should be handled by Azure or if it needs to be in the application itself. Are there any concerns one should consider?

best, 
Johannes

**Comment by Johschmidt43** [comment]
Thank you very much for the response @JonasKs. Are you ok if I open a PR in which I add one or few lines?

**Comment by JonasKs** [comment]
Yes😊
